[build]
  # Directory to publish your static site
  publish = "public"
  # Directory containing Netlify functions
  functions = "netlify-functions"

[functions]
  # Set the timeout for functions (in seconds)
  timeout = 20
